# SPDX-FileCopyrightText: 2024 The TetriQ authors
#
# SPDX-License-Identifier: CC0-1.0

max_clients=128
max_incoming_bandwidth=0
max_outgoing_bandwidth=0
client_timeout=1000
listen_address="0.0.0.0"
listen_port=31457
ticks_per_second=60

[game]
ticks_per_second=5
width=12
height=22